services:
  audio2mqtt:
    build: .
    image: audio2mqtt:local
    container_name: audio2mqtt
    env_file: .env
    environment:
      TSPROTO_DUMP_LICENSE: "1"
    ports:
      - "15000:15000"
      - "8080:8080"
    volumes:
      - ./models:/models
      - ./output:/output
      - ./config:/config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
